---
title: "Analysis"
author: "Charlotte Dawson"
date: "31/07/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.path = "results/figures/"
  )
```

## Fake analysis

A fake analysis which uses packages from CRAN (ggplot2), 
Bioconductor (limma), and github (ggprism).

### Load libraries

```{r}
library(ggplot2)
library(ggprism)
library(limma)

set.seed(1)
```

### Output figures

Generate an MA plot.

```{r}
MA <- new("MAList")
MA$A <- runif(300, 4, 16)
MA$M <- rt(300, df = 3)

# Spike-in values
MA$M[1:3] <- 0
MA$M[4:6] <- 3
MA$M[7:9] <- -3

status <- rep("Gene",300)
status[1:3] <- "M=0"
status[4:6] <- "M=3"
status[7:9] <- "M=-3"
values <- c("M=0","M=3","M=-3")
col <- c("blue","red","green")

# base plot with limma
plotMA(MA,main="MA-Plot with 12 spiked-in points",
       status=status, values=values, hl.col=col)

# ggplot with ggprism theme
MA.df <- data.frame(MA$M, MA$A, status, colour = status != "Gene")

ggplot(MA.df, aes(x = MA.A, y = MA.M, colour = colour)) + 
  geom_point() + 
  theme_prism() + 
  scale_color_prism("colorblind_safe")
```
